### ISSUE TITLE
Uh doesn't work as advertised

### ISSUE THREAD

**Issue by KDot227** [Smug246/luna-injection#1]
No

**Comment by KDot227** [comment]
+ Smd

**Comment by Smug246** [comment]
smh

**Comment by KDot227** [comment]
> smh 

Send server inv

**Comment by ItzJustError** [comment]
> Send server inv
https://discord.gg/Cdyes9Rxtk

**Comment by KDot227** [comment]
> > Send server inv
> > https://discord.gg/Cdyes9Rxtk

not yours 😭

**Comment by ItzJustError** [comment]
> > > Send server inv
> > > https://discord.gg/Cdyes9Rxtk
> 
> not yours 😭 

yeah no shit, it's Smugs (on his profile)

**Comment by lokzz** [comment]
yea some idiot put an extra line break
![image](https://github.com/Smug246/luna-injection/assets/50368061/141fbfd5-e92a-4e2e-b5ef-e38c76649727)
-- a saved-by-dumbness user
